#python scripts/launcher.py --config config/cross01_2_5.json
#python scripts/launcher.py --config config/cross01_5_5.json
#python scripts/launcher.py --config config/cross01_10_10.json
#python scripts/launcher.py --config config/cross01_10_30.json
#python scripts/launcher.py --config config/cross01_30_10.json
#python scripts/launcher.py --config config/cross01_30_30.json
#python scripts/launcher.py --config config/cross01_10_30_bn.json
#python scripts/launcher.py --config config/cross01_10_30_dp.json
#python scripts/launcher.py --config config/cross01_10_30_bn_dp.json
#python scripts/launcher.py --config config/cross01_10_30_polar.json
python scripts/launcher.py --config config/omnet_2_5.json
python scripts/launcher.py --config config/omnet_5_5.json
python scripts/launcher.py --config config/omnet_10_10.json
python scripts/launcher.py --config config/omnet_10_30.json
#python scripts/launcher.py --config config/omnet_30_10.json
#python scripts/launcher.py --config config/omnet_30_30.json
#python scripts/launcher.py --config config/omnet_10_30_bn.json
#python scripts/launcher.py --config config/omnet_10_30_dp.json
#python scripts/launcher.py --config config/omnet_10_30_bn_dp.json
#python scripts/launcher.py --config config/omnet_10_30_polar.json